### ISSUE TITLE
Tempo and Pitch

### ISSUE THREAD

**Issue by devikaramje** [edimuj/speechcapture#4]
Is it possible to get pitch (http://stackoverflow.com/questions/40984462/get-mic-audio-in-android-audiocontext - I think this will work) and tempo (http://stackoverflow.com/questions/30110701/how-can-i-use-js-webaudioapi-for-beat-detection) from mic input? @edimuj

**Comment by edimuj** [comment]
Yes, it should be possible to do that, but as the name implies this library is specialized to detect and capture speech, in for example speech detection, recognition applications, and other cases where voice-based mic input is needed to be sent to a server, so I haven't actually thought about implementing pitch and tempo detection since that can be done without this library simply relying on getUsermedia + Web Audio nodes as in those StackOverflow threads you posted.

You're of course welcome to fork this project if you want to have a go at extending it with that type of specialized functionality.
